meta_title: "Fantasy ProLeague"
meta_description: "Le seul et unique jeu Fantasy football de la ligue belge!"
meta_image: "stadium2.jpg" # Une image dans votre dossier app/assets/images/
# twitter_account: "@nomdevotrecompte" # indispensable pour les Twitter Cards
